apiVersion: apps/v1
kind: Deployment

metadata:
  name: mathsapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: mathsapp

  template:
    metadata:
      labels:
        app: mathsapp

    spec:
      containers:
      - name: mathsapp

        image: iheanyi014/mathsapp:v1

        ports:
        - containerPort: 5049